apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: pg-admin
  name: pg-admin-svc
  namespace: postgre
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30010
  selector:
    run: pg-admin
  type: NodePort
status:
  loadBalancer: {}
