apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pg-admin
  name: pg-admin
  namespace: postgre
spec:
  containers:
  - image: dpage/pgadmin4
    name: pg-admin
    ports:
     - containerPort: 80
       name: http-web
    env:
      - name: PGADMIN_DEFAULT_EMAIL
        value: user@domain.com
      - name: PGADMIN_DEFAULT_PASSWORD
        value: SuperSecret        
        
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
