apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pg-db
  name: pg-db
  namespace: postgre
spec:
  containers:
  - image: postgres
    name: pg-db
    ports:
     - containerPort: 5432
       name: tcp
    env:
      - name: POSTGRES_PASSWORD
        value: mysecretpassword
      - name: POSTGRES_USER
        value: postgres        
        
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
