apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: pg-db
  name: pg-db-svc
  namespace: postgre
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    run: pg-db
status:
  loadBalancer: {}
